---
abstract: 'Perl interface to interact with the Weebly API.'
author:
  - 'Rishwanth Yeddula <ryeddula@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Weebly
provides:
  WWW::Weebly:
    file: lib/WWW/Weebly.pm
    version: 0.01
  WWW::Weebly::TieFileWeebly:
    file: lib/WWW/Weebly/TieFileWeebly.pm
    version: 0
requires:
  HTTP::Tiny: 0
  URI::Escape: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.01
