---
abstract: 'Perl interface to interact with the Weebly API.'
author:
  - 'Rishwanth Yeddula <ryeddula@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.132140'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Weebly
provides:
  WWW::Weebly:
    file: lib/WWW/Weebly.pm
    version: 0.03
requires:
  HTTP::Tiny: 0
  URI::Escape: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.03
